

import { z } from 'zod';

export type QuizQuestion = {
    question: string;
    options?: string[]; // Optional for non-MCQ questions
    answer: string;
};

export type Flashcard = {
    front: string;
    back: string;
};

export type RagChunk = {
    score?: number;
    source: string;
    text: string;
}

export const RagOutputSchema = z.object({
  chunks: z.array(z.object({
    source: z.string(),
    text: z.string(),
    score: z.number().optional(),
  })).describe('The retrieved chunks from the knowledge base.'),
  finalAnswer: z.string().describe('The final answer generated by the AI.'),
});

export type RagOutput = z.infer<typeof RagOutputSchema>;

export type Message = {
    role: 'user' | 'assistant';
    content: string;
    audioData?: string;
    ragResponse?: VoiceTutorOutput;
};

export type TutorFormState = {
    message: string;
    role?: 'user' | 'assistant' | 'error';
    content?: string;
    errors?: {
        userMessage?: string[];
        documentText?: string[];
    };
};

export type TutorContextFormState = {
    message: string;
    documentText?: string;
    errors?: {
        text?: string[];
        file?: string[];
    };
};

export type RagFormState = {
    message: string;
    errors?: {
        question?: string[];
    };
    ragResponse?: RagOutput;
};


export const VoiceTutorOutputSchema = z.object({
  transcribedQuestion: z.string().describe("The user's question, transcribed from their voice input."),
  assistantResponse: z.string().describe('The AI tutor\'s text response.'),
  audioData: z.string().describe('The base64 encoded WAV audio data of the response.'),
  chunks: z.array(z.object({
    source: z.string(),
    text: z.string(),
  })).optional().describe('The retrieved chunks from the knowledge base.'),
});

export type VoiceTutorOutput = z.infer<typeof VoiceTutorOutputSchema>;

export type RagVoiceFormState = {
    message: string;
    errors?: {
        questionAudio?: string[];
        language?: string[];
    };
    response?: VoiceTutorOutput;
};


export type CurriculumContent = {
  id: string;
  subject: string;
  grade: number;
  board: string;
  chapter: number;
  chapterName: string;
  topic: string;
  content: string;
  urduContent: string;
  examples: string[];
  keywords: string[];
  embedding: number[];
  createdAt: string;
}

export type CurriculumDocument = {
  id: string;
  sourceName: string;
  chunkNumber: number;
  text: string;
  embedding?: number[];
  userId?: string;
};

// Schemas for Study Suite
export const StudyGuideSchema = z.object({
    summary: z.string().describe("A concise summary of the provided text."),
    keyPoints: z.array(z.string()).describe("A list of the most important key points or takeaways."),
    practiceQuestions: z.array(z.object({
        question: z.string().describe("A practice question based on the text."),
        answer: z.string().describe("The correct answer to the practice question.")
    })).describe("A list of practice questions with answers.")
});

export const AudioLessonSchema = z.object({
    title: z.string().optional().describe("The title of the audio lesson."),
    script: z.array(z.object({
        speaker: z.enum(["Tutor", "Student"]).describe("The speaker of the dialogue line."),
        dialogue: z.string().describe("The dialogue text for this speaker."),
    })).describe("A conversational script between two voices explaining the content."),
    audioData: z.string().optional().describe("Base64 encoded audio data for the lesson.")
});

export const ConceptMapSchema = z.object({
    mermaidGraph: z.string().describe("A MermaidJS graph diagram representing the key concepts and their relationships. Use a graph TD layout."),
});

export const StudySuiteInputSchema = z.object({
  text: z.string().describe('The notes or learning material to generate the study suite from.'),
  subject: z.string().optional(),
  grade: z.string().optional(),
  chapter: z.string().optional(),
  generate: z.object({
    guide: z.boolean().optional(),
    audio: z.boolean().optional(),
    map: z.boolean().optional(),
    flashcards: z.boolean().optional(),
    quiz: z.boolean().optional(),
  }),
});
export type StudySuiteInput = z.infer<typeof StudySuiteInputSchema>;

export const StudySuiteOutputSchema = z.object({
  guide: StudyGuideSchema.optional(),
  audio: AudioLessonSchema.optional(),
  map: ConceptMapSchema.optional(),
  flashcards: z.array(z.object({ front: z.string(), back: z.string() })).optional(),
  quiz: z.array(z.object({
    question: z.string(),
    options: z.array(z.string()).optional(),
    answer: z.string(),
  })).optional(),
});
export type StudySuiteOutput = z.infer<typeof StudySuiteOutputSchema>;

export type StudySuiteFormState = {
  message: string;
  errors?: {
    text?: string[];
  };
  output?: StudySuiteOutput;
};

// Defines the structured output for the notes
const NoteSectionSchema = z.object({
    heading: z.string().describe('The heading for this section of the notes.'),
    content: z.array(z.string()).describe('An array of bullet points or paragraphs for this section.'),
});

export const NotesOutputSchema = z.object({
  title: z.string().describe('The main title of the study notes.'),
  summary: z.string().describe('A brief, one to two-sentence summary of the entire text.'),
  sections: z.array(NoteSectionSchema).describe('An array of note sections, each with a heading and content.'),
  diagram: z.string().url().optional().describe("A URL (usually a data URI) for a generated diagram image related to the notes' content."),
  conceptMap: z.string().optional().describe("A MermaidJS graph diagram representing the key concepts and their relationships."),
});
export type NotesOutput = z.infer<typeof NotesOutputSchema>;


export type NotesFormState = {
  message: string;
  errors?: {
    text?: string[];
    prompt?: string[];
  };
  notes?: NotesOutput;
};

export type PresentationSlide = {
  title: string;
  content: string[];
  imageUrl?: string;
};

export type PresentationData = {
  title: string;
  agenda: string[];
  slides: PresentationSlide[];
};

export type PresentationFormState = {
    message: string;
    errors?: {
        text?: string[];
        topic?: string[];
    };
    presentation?: PresentationData;
};

export type ImportantTopic = {
  topic: string;
  frequency: number;
  relatedQuestions: string[];
};

export type ImportantQuestionsFormState = {
    message: string;
    errors?: {
        questions?: string[];
    };
    importantTopics?: ImportantTopic[];
};


export type QuizResult = {
    id?: string;
    topic: string;
    score: number;
    status: 'Passed' | 'Failed';
    completedAt: any; // Using `any` for Firestore Timestamp compatibility
};

export type YoutubeSummarizerFormState = {
    message: string;
    errors?: {
        videoUrl?: string[];
    };
    summary?: string;
};
